skip some bridge hacks
vscode $ git rebase upstream/main
Auto-merging src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
CONFLICT (content): Merge conflict in src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
error: could not apply 0cbdb97a823... codigo: port progrium/s patches to make the codigo bridge work
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 0cbdb97a823... # codigo: port progrium/s patches to make the codigo bridge work
vscode $ git rebase --skip
Auto-merging src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
CONFLICT (content): Merge conflict in src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
error: could not apply f4fd2293099... codigo: add _bridge & _bridge_port messages
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply f4fd2293099... # codigo: add _bridge & _bridge_port messages
vscode $ git rebase --skip
Auto-merging src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
CONFLICT (content): Merge conflict in src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
error: could not apply 8b30a27743e... codigo: remove _bridge
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 8b30a27743e... # codigo: remove _bridge
vscode $ git rebase --skip
Auto-merging src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
CONFLICT (content): Merge conflict in src/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html
error: could not apply 377819c9a56... codigo: remove _bridge_port
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 377819c9a56... # codigo: remove _bridge_port
vscode $ git rebase --skip
Successfully rebased and updated refs/heads/main.